package main

import (
	"encoding/csv"
	"encoding/json"
	"log"
	"os"
	"time"
)

var data = `[{"id":"86","name":"Mobil","sub_categories":[{"id":"198","name":"Mobil Bekas"},{"id":"4760","name":"Aksesori"},{"id":"4762","name":"Audio Mobil"},{"id":"4759","name":"Spare Part"},{"id":"4761","name":"Velg dan Ban"},{"id":"4662","name":"Truk & Kendaraan Komersial"}]},{"id":"88","name":"Properti","sub_categories":[{"id":"5158","name":"Dijual: Rumah & Apartemen"},{"id":"5160","name":"Disewakan: Rumah & Apartemen"},{"id":"4827","name":"Tanah"},{"id":"4833","name":"Indekos"},{"id":"5154","name":"Dijual: Bangunan Komersil"},{"id":"5156","name":"Disewakan: Bangunan Komersil"}]},{"id":"87","name":"Motor","sub_categories":[{"id":"200","name":"Motor Bekas"},{"id":"4823","name":"Aksesoris"},{"id":"4824","name":"Helm"},{"id":"4822","name":"Spare Part"}]},{"id":"97","name":"Jasa & Lowongan Kerja","sub_categories":[{"id":"226","name":"Lowongan"},{"id":"227","name":"Cari Pekerjaan"},{"id":"228","name":"Jasa"}]},{"id":"92","name":"Elektronik & Gadget","sub_categories":[{"id":"208","name":"Handphone"},{"id":"209","name":"Tablet"},{"id":"215","name":"Aksesoris HP & Tablet"},{"id":"211","name":"Fotografi"},{"id":"214","name":"Elektronik Rumah Tangga"},{"id":"212","name":"Games & Console"},{"id":"213","name":"Komputer"},{"id":"4952","name":"Lampu"},{"id":"210","name":"TV & Audio, Video"}]},{"id":"94","name":"Hobi & Olahraga","sub_categories":[{"id":"217","name":"Alat-alat Musik"},{"id":"218","name":"Olahraga"},{"id":"219","name":"Sepeda & Aksesoris"},{"id":"222","name":"Handicrafts"},{"id":"4964","name":"Barang Antik"},{"id":"220","name":"Buku & Majalah"},{"id":"221","name":"Koleksi"},{"id":"223","name":"Mainan Hobi"},{"id":"4975","name":"Musik & Film"},{"id":"235","name":"Hewan Peliharaan"}]},{"id":"89","name":"Rumah Tangga","sub_categories":[{"id":"4845","name":"Makanan & Minuman"},{"id":"4835","name":"Mebel"},{"id":"4836","name":"Dekorasi Rumah"},{"id":"4842","name":"Konstruksi dan Taman"},{"id":"4841","name":"Jam"},{"id":"4844","name":"Lampu"},{"id":"202","name":"Perlengkapan Rumah"},{"id":"4843","name":"Lain-lain"}]},{"id":"98","name":"Keperluan Pribadi","sub_categories":[{"id":"230","name":"Fashion Wanita"},{"id":"229","name":"Fashion Pria"},{"id":"231","name":"Jam Tangan"},{"id":"5095","name":"Pakaian Olahraga"},{"id":"232","name":"Perhiasan"},{"id":"233","name":"Make Up & Parfum"},{"id":"5123","name":"Terapi & Pengobatan"},{"id":"234","name":"Perawatan"},{"id":"5126","name":"Nutrisi & Suplemen"},{"id":"5124","name":"Lainnya"}]},{"id":"96","name":"Perlengkapan Bayi & Anak","sub_categories":[{"id":"5049","name":"Pakaian"},{"id":"224","name":"Perlengkapan Bayi"},{"id":"5048","name":"Perlengkapan Ibu Bayi"},{"id":"5142","name":"Boneka & Mainan Anak"},{"id":"5046","name":"Buku Anak-anak"},{"id":"5053","name":"Stroller"},{"id":"5047","name":"Lain-lain"}]},{"id":"90","name":"Kantor & Industri","sub_categories":[{"id":"203","name":"Peralatan Kantor"},{"id":"5090","name":"Perlengkapan Usaha"},{"id":"4846","name":"Mesin & Keperluan Industri"},{"id":"4852","name":"Stationery"},{"id":"4853","name":"Lain-lain"}]}]`

type AutoGenerated []struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	SubCategories []struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	} `json:"sub_categories"`
}

func main() {
	// service
	service := newCsvRecordService()
	go service.run("olx.csv")
	//
	a := AutoGenerated{}
	err := json.Unmarshal([]byte(data), &a)
	if err != nil {
		panic(err)
	}
	for _, v := range a {
		for _, vv := range v.SubCategories {
			res := make([]string, 0, 4)
			res = append(res, v.ID, v.Name, vv.ID, vv.Name)
			service.ch <- res
		}
	}
	time.Sleep(time.Second * 3)
}

// 处理用户上报日志服务
type CsvRecordService struct {
	// 通道大小
	len int
	// 缓存消息的通道
	ch chan []string
}

func newCsvRecordService() *CsvRecordService {
	return &CsvRecordService{
		len: 128,
		ch:  make(chan []string, 128),
	}
}

func (c *CsvRecordService) run(name string) {
	f, err := os.Create(name)
	defer f.Close()

	if err != nil {
		log.Fatalln("failed to open file", err)
	}

	w := csv.NewWriter(f)
	defer w.Flush()
	header := []string{"id", "name", "sub_id", "sub_name"}
	w.Write(header)
	for {
		select {
		case ch := <-c.ch:
			w.Write(ch)
		case <-time.After(time.Second * 2):
			w.Flush()
		}
	}
}
